<?php

namespace ServicesBundle\Repository;

/**
 * CommentaireServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
