<?php

namespace ServicesBundle\Repository;

/**
 * NotificationServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationServiceRepository extends \Doctrine\ORM\EntityRepository
{

}
