<?php

namespace ServicesBundle\Repository;

/**
 * PostulerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostulerRepository extends \Doctrine\ORM\EntityRepository
{
}
