<?php

namespace ServicesBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function historiqueJeune($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("Select s from ServicesBundle:Service s where s.userAssocie.id =:k ")
            ->setParameter(':k', $id);
        return $query->getResult();

    }
    public function historiqueAge($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("Select s from ServicesBundle:Service s where s.user.id =:k ")
            ->setParameter(':k', $id);
        return $query->getResult();

    }
}
