<?php

namespace ChatRoomBundle\Repository;

/**
 * CommentaireChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireChatRepository extends \Doctrine\ORM\EntityRepository
{
}
