<?php

namespace ChatRoomBundle\Repository;

/**
 * CommentaireChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireChatRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllComments($idPublication)
    {
        //return $this->findAll();
        $query=$this->getEntityManager()
            ->createQuery("SELECT c FROM ChatRoomBundle:CommentaireChat c "
                ."WHERE c.publication = :idPublication "
                ."ORDER BY c.dateCommentaire DESC ")
            ->setParameter(':idPublication',$idPublication);
        return $query->getResult();
    }
}
