<?php

namespace ChatRoomBundle\Repository;

/**
 * DiscussionIndivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscussionIndivRepository extends \Doctrine\ORM\EntityRepository
{
}
