<?php

namespace ChatRoomBundle\Repository;

/**
 * DiscussionGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscussionGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
