<?php

namespace ChatRoomBundle\Repository;

/**
 * GroupeSujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeSujetRepository extends \Doctrine\ORM\EntityRepository
{
}
