<?php

namespace ChatRoomBundle\Repository;

/**
 * LiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiveRepository extends \Doctrine\ORM\EntityRepository
{
}
