<?php

namespace ChatRoomBundle\Repository;

/**
 * MembreGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreGroupeRepository extends \Doctrine\ORM\EntityRepository
{

    public function getListGroupMembers($groupe_id, $user_id,$username,$nom,$prenom,$offset =0, $maxResult = 100)
    {
        //return $this->findAll();
        $query=$this->getEntityManager()
            ->createQuery("SELECT u.id, u.username, u.nom, u.prenom FROM ChatRoomBundle:MembreGroupe m "
                ."JOIN m.groupe g "
                ."JOIN m.user u "
                ."WHERE m.groupe = :groupe "
                ."AND u.username LIKE :username "
                ."AND u.prenom LIKE :prenom "
                ."AND u.nom LIKE :nom "
                ."AND ( "
                    ."g.type in ('private','public')"
                    ."OR :user_id in ("
                        ."SELECT u2.id FROM ChatRoomBundle:MembreGroupe m2 "
                        ."JOIN m2.user u2 "
                        ."JOIN m2.groupe g2 "
                        ."WHERE g2.id = :groupe "
                    .") "
                .") ")
            ->setParameter(':groupe',$groupe_id)
            ->setParameter(':user_id',$user_id)
            ->setParameter(":username","%".$username."%")
            ->setParameter(":nom","%".$nom."%")
            ->setParameter(":prenom","%".$prenom."%")
            ->setFirstResult($offset)
            ->setMaxResults($maxResult);
        return $query->getResult();
    }

    public function getListOfUsersToInvite($groupe_id,$username,$nom,$prenom,$offset =0, $maxResult = 100)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT u.id, u.username, u.nom, u.prenom from HappyOldsMainBundle:User u "
                ."WHERE u.username LIKE :username "
                ."AND u.prenom LIKE :prenom "
                ."AND u.nom LIKE :nom "
                ."AND u.id NOT IN ("
                    ."SELECT u2.id FROM ChatRoomBundle:MembreGroupe m "
                    ."JOIN m.user u2 "
                    ."JOIN m.groupe g "
                    ."WHERE g.id = :groupe "
                .") ")
            ->setParameter(":groupe",$groupe_id)
            ->setParameter(":username","%".$username."%")
            ->setParameter(":nom","%".$nom."%")
            ->setParameter(":prenom","%".$prenom."%")
            ->setFirstResult($offset)
            ->setMaxResults($maxResult);
        return $query->getResult();
    }
}
