<?php

namespace ChatRoomBundle\Repository;

/**
 * MembreGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
