<?php

namespace ChatRoomBundle\Repository;

/**
 * NotificationChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationChatRepository extends \Doctrine\ORM\EntityRepository
{
}
