<?php

namespace ChatRoomBundle\Repository;

/**
 * PublicationGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
