<?php

namespace HappyOldsMainBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByV($v){
        $query = $this->getEntityManager()
            ->createQuery("Select n from HappyOldsMainBundle:Notification n where n.parameters like :k ")
            ->setParameter('k','%'.$v.'%');
        return $query->getOneOrNullResult();
    }
}
