# home page
happy_olds_main_homepage:
    path:     /home
    defaults: { _controller: HappyOldsMainBundle:Default:accueil }

happy_olds_main_page:
    path:     /
    defaults: { _controller: HappyOldsMainBundle:Default:mainPage }

# login and register pages
happy_olds_main_login:
    path:     /login
    defaults: { _controller: HappyOldsMainBundle:Default:index }
happy_olds_main_api_login:
    path:     /api/login
    defaults: { _controller: HappyOldsMainBundle:Default:_login }
    methods: POST
happy_olds_main_register:
    path:     /register
    defaults: { _controller: HappyOldsMainBundle:Default:register }
happy_olds_main_jeune:
    path:     /homejeune
    defaults: { _controller: HappyOldsMainBundle:Default:accueiljeune }
happy_olds_main_admin:
    path:     /admin
    defaults: { _controller: HappyOldsMainBundle:Default:accueiladmin }

forbidden_403:
    path:     /forbidden
    defaults: { _controller: HappyOldsMainBundle:Default:error403 }

modifier_profil:
    path:     /profil
    defaults: { _controller: HappyOldsMainBundle:Default:profil }

