services:
#    happy_olds_main.example:
#        class: HappyOldsMainBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    authentication.handler.login_success_handler:
        class:  HappyOldsMainBundle\Security\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']
    access.handler.access_denied_handler:
        class: HappyOldsMainBundle\Security\AccessDeniedHandler
        public: false
        arguments: ["@templating","@router","@session"]

    security.auth_handler:
        class:      HappyOldsMainBundle\Security\AuthenticationHandler
        public:     false
        arguments:  ['@router','@session','@security.authorization_checker']

