services:
#    happy_olds_main.example:
#        class: HappyOldsMainBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    authentication.handler.login_success_handler:
        class:  HappyOldsMainBundle\Security\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']
