event_index:
    path:     /
    defaults: { _controller: "EventsBundle:Event:index" }
    methods:  GET

event_show:
    path:     /{id}/show/
    defaults: { _controller: "EventsBundle:Event:show" }
    methods:  GET

event_new:
    path:     /new/
    defaults: { _controller: "EventsBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /{id}/edit/
    defaults: { _controller: "EventsBundle:Event:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /{id}/delete/
    defaults: { _controller: "EventsBundle:Event:delete" }
    methods:  DELETE

event_affiche:
    path:     /affiche/
    defaults: { _controller: "EventsBundle:Event:affiche" }
    methods:  GET

event_voir:
    path:     /voir/
    defaults: { _controller: "EventsBundle:Event:voir" }
    methods:  GET

event_rate:
    path:     /{id}/rate/
    defaults: { _controller: "EventsBundle:Event:rate" }
    methods:  GET

event_venir:
    path:     /venir/
    defaults: { _controller: "EventsBundle:Event:venir" }
    methods:  GET

event_note:
    path:     /note/
    defaults: { _controller: "EventsBundle:Rate:ajout" }
    methods:  POST

event_participer:
    path:     /participer/
    defaults: { _controller: "EventsBundle:Event:participer" }

event_annuler:
     path:     /annuler/
     defaults: { _controller: "EventsBundle:Event:annuler" }

event_show4:
    path:     /{id}/show4/
    defaults: { _controller: "EventsBundle:Event:show4" }
    methods:  GET

event_delete3:
        path:     /delete3/
        defaults: { _controller: "EventsBundle:Event:delete3" }

event_rechercher:
        path:     /rechercher/
        defaults: { _controller: "EventsBundle:Event:rechercher" }

