services_index:
    path:     /
    defaults: { _controller: "ServicesBundle:Service:index" }
    methods:  GET
services_publier:
    path:     /publier
    defaults: { _controller: "ServicesBundle:Service:publier" }
    methods:  GET
services_postuler:
    path:     /postuler
    defaults: { _controller: "ServicesBundle:Service:postuler" }
    methods:  GET

services_show:
    path:     /{id}/show
    defaults: { _controller: "ServicesBundle:Service:show" }
    methods:  GET

services_new:
    path:     /new
    defaults: { _controller: "ServicesBundle:Service:new" }
    methods:  [GET, POST]

services_edit:
    path:     /{id}/edit
    defaults: { _controller: "ServicesBundle:Service:edit" }
    methods:  [GET, POST]

services_delete:
    path:     /delete
    defaults: { _controller: "ServicesBundle:Service:delete" }
    methods:  [GET, POST]
services_condidat:
    path:     /condidats
    defaults: { _controller: "ServicesBundle:Service:listcondidat" }
    methods:  [GET, POST]
services_Acceptcondidat:
    path:     /accept
    defaults: { _controller: "ServicesBundle:Service:acceptcondidat" }
    methods:  [GET, POST]
services_Eval:
    path:     /eval
    defaults: { _controller: "ServicesBundle:Service:eval" }
    methods:  [GET, POST]
services_history:
    path:     /history
    defaults: { _controller: "ServicesBundle:Service:history" }
    methods:  [GET, POST]
services_list:
    path:     /list
    defaults: { _controller: "ServicesBundle:Service:list" }
    methods:  [GET, POST]
services_DeleteAdm:
    path:     /list
    defaults: { _controller: "ServicesBundle:Service:DeleteAdm" }
    methods:  [GET, POST]
commentaire:
    path:     /commentaire
    defaults: { _controller: "ServicesBundle:Service:addCom" }
    methods:  [GET, POST]