chat_room_group_list:
    path:     /
    defaults: { _controller: ChatRoomBundle:Groupe:list }

chat_room_group_consult:
    path:     /group
    defaults: { _controller: ChatRoomBundle:Groupe:consult }

chat_room_group_add:
    path:     /add
    defaults: { _controller: ChatRoomBundle:Groupe:add }

chat_room_group_update:
    path:     /update
    defaults: { _controller: ChatRoomBundle:Groupe:update }

chat_room_group_delete:
    path:     /delete
    defaults: { _controller: ChatRoomBundle:Groupe:delete }

chat_room_group_join:
    path:     /join
    defaults: { _controller: ChatRoomBundle:Groupe:join }

chat_room_group_leave:
    path:     /leave
    defaults: { _controller: ChatRoomBundle:Groupe:leave }
