chat_room_group_list:
    path:     /
    defaults: { _controller: ChatRoomBundle:Groupe:liste }

chat_room_group_consult:
    path:     /group
    defaults: { _controller: ChatRoomBundle:Groupe:consult }

chat_room_group_add:
    path:     /add
    defaults: { _controller: ChatRoomBundle:Groupe:add }