chat_room_publication_add:
    path:     /add
    defaults: { _controller: ChatRoomBundle:PublicationGroupe:add }

chat_room_publication_delete:
    path:     /delete
    defaults: { _controller: ChatRoomBundle:PublicationGroupe:delete }

chat_room_publication_consult:
    path:      /consult
    defaults: { _controller: ChatRoomBundle:PublicationGroupe:consult }

chat_room_publication_update:
    path:      /update
    defaults: { _controller: ChatRoomBundle:PublicationGroupe:update }
