medical:
    resource: "@MedicalBundle/Resources/config/routing.yml"
    prefix:   /medical

services:
    resource: "@ServicesBundle/Resources/config/routing.yml"
    prefix:   /services

events:
    resource: "@EventsBundle/Resources/config/routing.yml"
    prefix:   /events

chat_room:
    resource: "@ChatRoomBundle/Resources/config/routing.yml"
    prefix:   /chat

happy_olds_main:
    resource: "@HappyOldsMainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
