chat_room:
    resource: "@ChatRoomBundle/Resources/config/routing.yml"
    prefix:   /chatRoom

happy_olds_main:
    resource: "@HappyOldsMainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
