# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_AGE: ROLE_USER
        ROLE_JEUNE: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
         in_memory:
             memory:
                 users:
                     admin: { password: '$2y$13$O4gZyqea3yqa0S1C3JLUYO3WSP.eLiE7XxgQqyzeFs/mBtCIc40sC', roles: [ 'ROLE_ADMIN' ] }
         fos_userbundle:
                     id: fos_user.user_provider.username
         chain_provider:
              chain:
                 providers: [in_memory, fos_userbundle]

    firewalls:
        main:
          pattern: ^/
          form_login:
              provider: chain_provider
              csrf_token_generator: security.csrf.token_manager
              success_handler: authentication.handler.login_success_handler
              #always_use_default_target_path: false
              #default_target_path:    happy_olds_main_homepage
          logout: true
          anonymous: true
          access_denied_handler: access.handler.access_denied_handler

    access_control:
      - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin, role: ROLE_ADMIN }
      - { path: ^/, role: ROLE_USER }
      #- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
      #- { path: ^/affichage, role: ROLE_JEUNE }

