<?php

namespace MedicalBundle\Repository;

/**
 * CommentaireMedicalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireMedicalRepository extends \Doctrine\ORM\EntityRepository
{
}
