<?php

namespace MedicalBundle\Repository;

/**
 * NotificationMedicalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationMedicalRepository extends \Doctrine\ORM\EntityRepository
{
}
