<?php

namespace MedicalBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function MyfindAll($titre){
        $query=$this->getEntityManager()
            ->createQuery("Select q from MedicalBundle:Question q where q.titre LIKE :t ")
            ->setParameter(':t','%'.$titre.'%');
        return $query->getResult();
    }
}
