<?php

namespace EventsBundle\Repository;

/**
 * CommentaireEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireEventsRepository extends \Doctrine\ORM\EntityRepository
{
}
