<?php

namespace EventsBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindall($user)
    {
        $query=$this->getEntityManager()
            ->createQuery(" SELECT m FROM EventsBundle:Event m WHERE m.id_user= :user ")
        ->setParameter(':user',$user);
        return $query->getResult();
    }

    public function participedIn($user){
        $query=$this->getEntityManager()
            ->createQuery(" SELECT e FROM EventsBundle:Event e "
                ." LEFT JOIN e.Participants p "
                ." WHERE p.user = :user and e.dateFin < current_date() ")
            ->setParameter(':user',$user);
        return $query->getResult();
    }
}
