<?php

namespace EventsBundle\Repository;

/**
 * NotificationEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationEventsRepository extends \Doctrine\ORM\EntityRepository
{
}
