chat_room_api_group_list:
    path:     /
    defaults: { _controller: ChatRoomBundle:Groupe:_list }

chat_room_api_group_consult:
    path:     /group
    defaults: { _controller: ChatRoomBundle:Groupe:_consult }

chat_room_api_group_add:
    path:     /add
    defaults: { _controller: ChatRoomBundle:Groupe:_add }

chat_room_api_group_update:
    path:     /update
    defaults: { _controller: ChatRoomBundle:Groupe:_update }

chat_room_api_group_delete:
    path:     /delete
    defaults: { _controller: ChatRoomBundle:Groupe:_delete }