all_service:
  path: service/all
  defaults: { _controller: "ServicesBundle:Api:all" }
one_service:
  path: service/{id}
  defaults: { _controller: "ServicesBundle:Api:findone" }
new_service:
  path: add
  defaults: { _controller: "ServicesBundle:Api:fawzi" }
postuler_service:
  path: postuler
  defaults: { _controller: "ServicesBundle:Api:postuler" }