Question_list:
    path:     /list
    defaults: { _controller: "MedicalBundle:Question:list" }


Question_DeleteAdm:
    path:     /del
    defaults: { _controller: "MedicalBundle:Question:DeleteAdm" }