all_question:
  path: /all
  defaults: { _controller: "MedicalBundle:api:all" }
one_question:
  path: /{id}
  defaults: { _controller: "MedicalBundle:api:findone" }
new_question:
  path: add
  defaults: { _controller: "MedicalBundle:Api:add" }